services:
  web:
    build: ./services/web
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    environment:
      - PORT=${WEB_PORT}
    depends_on:
      - auth
      - scanner
    networks:
      - public
      - web-auth
      - web-scanner
  
  auth:
    build: ./services/auth
    expose:
      - "${AUTH_PORT}"
    environment:
      - AUTH_PORT=${AUTH_PORT}
    networks:
      - web-auth

  scanner:
    build: ./services/scanner
    expose:
      - "${SCANNER_PORT}"
    environment:
      - SCANNER_PORT=${SCANNER_PORT}
    depends_on:
      - ml
    networks:
      - web-scanner
      - scanner-ml

  ml:
    build: ./services/ml
    expose:
      - "${ML_PORT}"
    environment:
      - ML_PORT=${ML_PORT}
    networks:
      - scanner-ml

networks:
  public:
  web-auth:
  web-scanner:
  scanner-ml:

#TODO: append Posgres/Redis/NATS + (maybe Kafka + K8t)
#TODO: сейчас `public` избыточно, однако в будующем можно добавить `reverse-proxy/API Gateway перед web`