with-expecter: true
dir: "internal/mocks"
outpkg: "mocks"
resolve-type-alias: false
disable-version-string: true
issue-845-fix: true
packages:
  github.com/MiralSNk/sitefrisk/services/scanner/internal/collector:
    interfaces:
      Collector: