// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	fact "github.com/MiralSNk/sitefrisk/services/scanner/internal/fact"

	mock "github.com/stretchr/testify/mock"
)

// MockCollector is an autogenerated mock type for the Collector type
type MockCollector struct {
	mock.Mock
}

type MockCollector_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCollector) EXPECT() *MockCollector_Expecter {
	return &MockCollector_Expecter{mock: &_m.Mock}
}

// Collect provides a mock function with given fields: ctx, targetURL
func (_m *MockCollector) Collect(ctx context.Context, targetURL string) ([]fact.Fact, error) {
	ret := _m.Called(ctx, targetURL)

	if len(ret) == 0 {
		panic("no return value specified for Collect")
	}

	var r0 []fact.Fact
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]fact.Fact, error)); ok {
		return rf(ctx, targetURL)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []fact.Fact); ok {
		r0 = rf(ctx, targetURL)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]fact.Fact)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, targetURL)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCollector_Collect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Collect'
type MockCollector_Collect_Call struct {
	*mock.Call
}

// Collect is a helper method to define mock.On call
//   - ctx context.Context
//   - targetURL string
func (_e *MockCollector_Expecter) Collect(ctx interface{}, targetURL interface{}) *MockCollector_Collect_Call {
	return &MockCollector_Collect_Call{Call: _e.mock.On("Collect", ctx, targetURL)}
}

func (_c *MockCollector_Collect_Call) Run(run func(ctx context.Context, targetURL string)) *MockCollector_Collect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCollector_Collect_Call) Return(_a0 []fact.Fact, _a1 error) *MockCollector_Collect_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCollector_Collect_Call) RunAndReturn(run func(context.Context, string) ([]fact.Fact, error)) *MockCollector_Collect_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCollector creates a new instance of MockCollector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCollector(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCollector {
	mock := &MockCollector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
